export const SAVE_NICKNAME = 'SAVE_NICKNAME';
export const SYNC_FOLLOWS_LIST = 'SYNC_FOLLOWS_LIST';
export const SAVE_FOLLOW_MESSAGE = 'SAVE_FOLLOW_MESSAGE';
export const NICKNAME_ERROR = 'NICKNAME_ERROR';
export const FOLLOWS_LIST_ERROR = 'FOLLOWS_LIST_ERROR';
export const FOLLOW_MESSAGE_ERROR = 'FOLLOW_MESSAGE_ERROR';
export const EXTENSION_ERROR = 'EXTENSION_ERROR';